# Generated by Django 2.2.1 on 2019-07-05 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('colony', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'sex',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.City')),
                ('sex', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Sex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
