# Generated by Django 2.2.1 on 2019-07-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='img',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
