# Generated by Django 2.2.1 on 2019-07-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_alumno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
