# Generated by Django 2.2.1 on 2019-07-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_profesor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='alumnos_list', to='alumno.Profesor'),
        ),
    ]
