# Generated by Django 2.2.1 on 2019-07-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'negocios',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='empleado.Negocio')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
