# Generated by Django 2.2.1 on 2019-07-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
