# Generated by Django 2.2.1 on 2019-07-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_negocio_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='status',
        ),
    ]
