# Generated by Django 2.2.1 on 2019-07-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_auto_20190705_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='negocio',
            new_name='re_negocio',
        ),
    ]
